apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: 'gitlab/gitlab-ce:latest'
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22
        volumeMounts:
          - name: gitlab-config
            mountPath: /etc/gitlab
          - name: gitlab-logs
            mountPath: /var/log/gitlab
          - name: gitlab-data
            mountPath: /var/opt/gitlab
        resources:
          limits:
            memory: "6Gi"
            cpu: "2"
        securityContext:
          privileged: true

      - name: gitlab-runner
        image: 'rakeshbasnet/gitlab-runner:latest'
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: gitlab-runner-config
            mountPath: /etc/gitlab-runner
      volumes:
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: gitlab-runner-config
          persistentVolumeClaim:
            claimName: gitlab-runner-config
      restartPolicy: Always
