apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
  namespace: gitlab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/gitlab/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
  namespace: gitlab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/gitlab/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
  namespace: gitlab
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/gitlab/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-runner-config-pv
  namespace: gitlab
spec:
  capacity:
    storage: 1Gi  # Adjust storage size based on your needs
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/gitlab-runner/config  # Path on the host where config will be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-config
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size based on your needs
