apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 1443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 1001
      targetPort: 22
  type: NodePort
